# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - jordyscrap

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_SENDER_MAIL: ${{ secrets.SENDER_MAIL }}
        envkey_MAIL_PASS: ${{ secrets.MAIL_PASS }}
        envkey_PG_HOST: ${{ secrets.PG_HOST }}
        envkey_PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        envkey_PG_USER: ${{ secrets.PG_USER }}
        envkey_PG_DATABSE: ${{ secrets.PG_DATABASE }}
        file_name: .env
        
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run tests
      run: python3 tests.py

    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.7'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jordyscrap'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_68b186e4471d49328fa2b10634e7da34 }}